name: CI
on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: cd game && npm ci
      - run: cd game && npm run build      # garante que compila
      - run: cd game && npx tsc --noEmit   # typecheck
      - run: cd game && npx eslint .       # lint (se quiser)
